/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author gerso
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
         setTitle("Inicio");
         setLocationRelativeTo(null);
         rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/iconos/menuu.png");
         rsscalelabel.RSScaleLabel.setScaleLabel(btns, "src/iconos/botonesconfac.png");
       
        btnConteo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFactorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btns = new javax.swing.JLabel();
        btnFactorial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnConteo = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPanel2.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btns.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 24)); // NOI18N
        getContentPane().add(btns, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 550, 110));

        btnFactorial.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnFactorial.setText("Factorial (n!)");
        btnFactorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnFactorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 170, 70));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 360, 180));

        btnConteo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnConteo.setText("Conteo (nxm)");
        btnConteo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConteoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConteo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 170, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 630, 440));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        try {
            VistaFactorial factorial = new VistaFactorial ();
            factorial.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            
             e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir la ventana Factorial: " + e.getMessage());
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir la ventana Conteo: " + e.getMessage());
        }

    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnConteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConteoActionPerformed
        try {
            VistaConteo conteo = new VistaConteo ();
            conteo.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnConteoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnConteo;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JLabel btns;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
