/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


import modelos.ModeloConteo;

/**
 *
 * @author javie
 */
public class VistaConteo extends javax.swing.JFrame {
    
    
    private ArrayList<JTextField> listaCampos;
    private JButton botonAgregar, botonCalcular;
   
    private List<JTextField> campos;
    private int contadorCampos = 0;
    private ModeloConteo modeloConteo;
    /**
     * Creates new form VistaConteo
     */
    public VistaConteo() {
        initComponents();
        modeloConteo = new ModeloConteo(this);
        setTitle("Calculadora de Producto");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(null);
        setVisible(true);// Usamos layout nulo para posicionamiento manual
        listaCampos = new ArrayList<>(); 
         
          panelCampos.setLayout(new GridLayout(0,2,10,10));
       
          
        agregarCampo();
        agregarCampo();
        
       
        
        
    }
   private void agregarCampo() {
       
       if(contadorCampos<10){
        JTextField nuevoCampo = new JTextField(100);
        nuevoCampo.setPreferredSize(new java.awt.Dimension(100, 10));
        panelCampos.add(nuevoCampo);
        listaCampos.add(nuevoCampo);
        contadorCampos++;
        panelCampos.revalidate();
        panelCampos.repaint();
       } else {
         javax.swing.JOptionPane.showMessageDialog(this, "No se pueden agregar más de 10 campos.");

       }
        
          
    }
   
   private void calcularProducto(){
   modeloConteo.limpiarValores(); 
    boolean hayErrores = false;

    for (JTextField campo : listaCampos) {
        String texto = campo.getText();
        try {
           double valor = Double.parseDouble(texto);
            modeloConteo.agregarValor(valor); 
        } catch (NumberFormatException e) {
            hayErrores = true;
            System.out.println("Error de formato en el campo: "+texto);
        }
    }

    if (hayErrores) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese solo números.");
    } else {
        double producto = modeloConteo.calcularProducto(); // Usa el modelo para calcular el producto
        resultadoLabel.setText("Resultado: " + producto);
        System.out.println("Productoc calculado: " + producto);
        
       
        resultadoLabel.revalidate();
        resultadoLabel.repaint();
        }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnConteo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelCampos = new javax.swing.JPanel();
        resultadoLabel = new javax.swing.JLabel();
        btnGenerarPdf = new javax.swing.JButton();
        btnAbrirPdf = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setText("Conteo");

        jLabel2.setText("Sustituya los datos de la formula siguiente : N X M");

        btnConteo.setText("Resolver");
        btnConteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConteoActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jButton1.setText("Volver al Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCamposLayout = new javax.swing.GroupLayout(panelCampos);
        panelCampos.setLayout(panelCamposLayout);
        panelCamposLayout.setHorizontalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        panelCamposLayout.setVerticalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        btnGenerarPdf.setText("Generar Pdf");
        btnGenerarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPdfActionPerformed(evt);
            }
        });

        btnAbrirPdf.setText("Abrir PDF");
        btnAbrirPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirPdfActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resultadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConteo)
                        .addGap(48, 48, 48)
                        .addComponent(btnLimpiar)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenerarPdf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAbrirPdf, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(140, 140, 140))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(panelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultadoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConteo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimpiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerarPdf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbrirPdf)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregarCampo();
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       this.dispose();
       Inicio volverMenu = new Inicio();
       volverMenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConteoActionPerformed
        // TODO add your handling code here:
        calcularProducto();
    }//GEN-LAST:event_btnConteoActionPerformed

    private void btnGenerarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPdfActionPerformed
         try {
            generar(resultadoLabel.getText());
            
        } catch (FileNotFoundException e) {
            
        } catch (DocumentException ex) {
            java.util.logging.Logger.getLogger(VistaConteo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(VistaConteo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarPdfActionPerformed

    private void btnAbrirPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirPdfActionPerformed
        if(!resultadoLabel.getText().isEmpty())
         abrir(resultadoLabel.getText());  
        else
            JOptionPane.showMessageDialog(null, "campo vaci0/ no se encuentra","Atencion",2);
    }//GEN-LAST:event_btnAbrirPdfActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        
        for(JTextField campo : listaCampos){
               campo.setText("");
        }
         resultadoLabel.setText("");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed
public void generar (String operacion) throws FileNotFoundException, DocumentException, IOException{
    
    if (!(resultadoLabel.getText().isEmpty())) {
        
    // Especifica la ruta de la carpeta de Descargas
        String carpetaDescargas = System.getProperty("user.home") + File.separator + "Downloads";
        String nombreArchivo = carpetaDescargas + File.separator + "semidios" + ".pdf";

        // Imprime la ruta del archivo para verificar
        System.out.println("Ruta del archivo PDF: " + nombreArchivo);

        // Usar FileOutputStream para crear el archivo PDF
        FileOutputStream archivo = null; // Inicializa la variable
        try {
            archivo = new FileOutputStream(nombreArchivo); // Asigna el archivo

            Document documento = new Document();
            PdfWriter.getInstance(documento, archivo);
            documento.open();
        VistaAnalisis analisis = new VistaAnalisis ();
        
            
            // Agrega contenido al PDF
            documento.add(new Paragraph("Resolución del problema"));
            documento.add(new Paragraph("Formula utilizada : n x m"));
            documento.add(new Paragraph ("descrpicion del problema"+ analisis.getDescripcionTexto()));
            StringBuilder procedimiento = new StringBuilder("Procedimiento del problema: ");
        for (JTextField campo : listaCampos) {
            String textoCampo = campo.getText();
            procedimiento.append(textoCampo).append(" * "); // Agregar texto de cada campo
        }
        // Eliminar la última coma y espacio si hay texto
        if (procedimiento.length() > 0) {
            procedimiento.setLength(procedimiento.length() - 2); // Eliminar última coma y espacio
        }
        documento.add(new Paragraph(procedimiento.toString()));
            documento.add(new Paragraph("Resultado del problema: " + resultadoLabel.getText()));
            documento.close();

            // Mensaje de éxito
            JOptionPane.showMessageDialog(null, "PDF creado de manera correcta en: " + nombreArchivo, "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error al crear el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DocumentException e) {
            JOptionPane.showMessageDialog(null, "Error al generar el documento PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Asegúrate de cerrar el archivo
            try {
                if (archivo != null) {
                    archivo.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cerrar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Debe llenar el campo", "Atención", JOptionPane.WARNING_MESSAGE);
    }
        
}
public void abrir(String nombre) {
    try {
        File path = new File (nombre + ".pdf");
        Desktop.getDesktop().open(path);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "campos","Atencion",2);
    }
   
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConteo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirPdf;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConteo;
    public javax.swing.JButton btnGenerarPdf;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel panelCampos;
    private javax.swing.JLabel resultadoLabel;
    // End of variables declaration//GEN-END:variables
}
